# Generated by Django 3.2.3 on 2021-10-28 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myplant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Profile_photo',
            field=models.ImageField(default='https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png', upload_to=''),
        ),
    ]
